set(MYSQL_INCLUDE_PATH
  "${PROJECT_BINARY_DIR}/Dependencies/mariadb-connector-c-3.4.9/include")
set(MYSQL_LIBRARY_DEBUG_PATH
  "${PROJECT_BINARY_DIR}/Dependencies/mariadb-connector-c-3.4.9/libmariadb/libmariadbclient.a")
set(MYSQL_LIBRARY_OPTIMIZED_PATH
  "${PROJECT_BINARY_DIR}/Dependencies/mariadb-connector-c-3.4.9/libmariadb/libmariadbclient.a")
set(OPEN_SSL_INCLUDE_PATH
  "${PROJECT_BINARY_DIR}/Dependencies/openssl-3.6.0/include")
set(OPEN_SSL_BASE_LIBRARY_DEBUG_PATH
  "${PROJECT_BINARY_DIR}/Dependencies/openssl-3.6.0/lib64/libcrypto.a")
set(OPEN_SSL_BASE_LIBRARY_OPTIMIZED_PATH
  "${PROJECT_BINARY_DIR}/Dependencies/openssl-3.6.0/lib64/libcrypto.a")
set(OPEN_SSL_LIBRARY_DEBUG_PATH
  "${PROJECT_BINARY_DIR}/Dependencies/openssl-3.6.0/lib64/libssl.a")
set(OPEN_SSL_LIBRARY_OPTIMIZED_PATH
  "${PROJECT_BINARY_DIR}/Dependencies/openssl-3.6.0/lib64/libssl.a")
set(SQLITE_INCLUDE_PATH
  "${PROJECT_BINARY_DIR}/Dependencies/sqlite-amalgamation-3510200")
set(SQLITE_LIBRARY_DEBUG_PATH
  "${PROJECT_BINARY_DIR}/Dependencies/sqlite-amalgamation-3510200/sqlite3.lib")
set(SQLITE_LIBRARY_OPTIMIZED_PATH
  "${PROJECT_BINARY_DIR}/Dependencies/sqlite-amalgamation-3510200/sqlite3.lib")
